title: "Global Tech Trends by Kuro"
email: contact@kuromin.co
description: >-
  Daily curated AI & Tech news, summarized for busy professionals. 
  Focusing on Autonomous Agents, Coding Trends, and the Future of Work.
baseurl: "/blog"
url: "https://kuromin-co.github.io"
twitter_username: kuromin_co
github_username: KUROmin-co

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Minima Skin specifics
header_pages:
  - about.md
  - index.md

# SEO Tag defaults
author: Kuro
lang: en
logo: https://github.com/KUROmin-co.png
social:
  name: Kuro
  links:
    - https://twitter.com/kuromin_co
    - https://github.com/KUROmin-co
