title: "Global Tech Trends by Kuro"
email: contact@kuromin.co
description: >- # this means to ignore newlines until "baseurl:"
  Daily curated AI & Tech news, summarized for busy professionals.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kuromin-co.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
plugins:
  - jekyll-feed
